"""Color roles for the typing area. Kept in one place so themes can override."""

STYLE_PENDING = "white"
STYLE_CORRECT = "grey42"
STYLE_CURRENT = "bold underline"
STYLE_WRONG_CURRENT = "bold red underline"
STYLE_CORRECTED = "dim yellow"
STYLE_IDLE = "dim"
STYLE_TREND_CONFIDENCE = "cyan"
STYLE_TREND_SPEED = "green"
STYLE_TREND_ACCURACY = "yellow"
